runtime: nodejs16
service: default
instance_class: F2
automatic_scaling:
  max_instances: 2
  min_instances: 1
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    secure: always
    redirect_http_response_code: 301
    static_files: dist/\1
    upload: dist/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/index.html
    upload: dist/index.html
env_variables:
  APP_URL: https://geyser.fund
  MIN_INITIAL_FUNDING: 1
  NODE_ENV: production
service_account: 'geyser-frontend-app-engine@geyser-mvp-prod.iam.gserviceaccount.com'
