runtime: nodejs16
service: frontend
instance_class: F2
env_variables:
  APP_URL: https://geyser.fund
  MIN_INITIAL_FUNDING: 1
  NODE_ENV: production
  REACT_APP_API_ENDPOINT: https://6-dot-default-dot-geyser-mvp-prod.us-central1.r.appspot.com
service_account: "geyser-frontend-app-engine@geyser-mvp-prod.iam.gserviceaccount.com"
