version: "3.9"
services:

  geyser-app:
    container_name: geyser-app
    build:
      context: .
      target: base
    command:  sh -c "yarn install && yarn dev"
    working_dir: /usr/app
    image:  geyser-app
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app:cached

  caddy:
    container_name: geyser-caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:cached
      - ./caddy/config:/config